In [1]:
import numpy as np
import pandas as pd

input_file = "baseDatosNumerica.csv"
df = pd.read_csv(input_file, header = 0, delimiter = ";")
# put the original column names in a python list
original_headers = list(df.columns.values)

In [2]:
type(df)
df.head()
df = df.dropna()

In [3]:
y = df["Incidente"]
X = df.drop(["Incidente"], axis=1)
X.head()

Codigo DANE  Dia = Lunes  Dia = Martes  Dia = Miercoles  Dia = Viernes  \
0     0.001614            1             0                0              0   
1     0.003788            1             0                0              0   
2     0.004474            1             0                0              0   
3     0.000000            1             0                0              0   
4     0.005086            1             0                0              0   

   Dia = Jueves  Dia = Sabado  Dia = Domingo  \
0             0             0              0   
1             0             0              0   
2             0             0              0   
3             0             0              0   
4             0             0              0   

   Arma empleada = ARMA BLANCA / CORTOPUNZANTE  \
0                                            1   
1                                            0   
2                                            0   
3                                            0   
4                                            0   

   Arma empleada = SIN EMPLEO DE ARMAS  ...  Arma empleada = JERINGA  \
0                                    0  ...                        0   
1                                    1  ...                        0   
2                                    1  ...                        0   
3                                    1  ...                        0   
4                                    1  ...                        0   

   Arma empleada = -  Arma empleada = VEHICULO  Arma empleada = MOTO  \
0                  0                         0                     0   
1                  0                         0                     0   
2                  0                         0                     0   
3                  0                         0                     0   
4                  0                         0                     0   

   Arma empleada = BICICLETA  Sexo = MASCULINO  Sexo = FEMENINO  Sexo = -  \
0                          0                 1                0         0   
1                          0                 1                0         0   
2                          0                 1                0         0   
3                          0                 1                0         0   
4                          0                 1                0         0   

   Edad  clase  
0  48.0    0.0  
1  39.0    0.0  
2  18.0    0.0  
3  15.0    0.0  
4  58.0    0.0  

[5 rows x 40 columns]

In [4]:
y.head()

0    Amenaza
1    Amenaza
2    Amenaza
3    Amenaza
4    Amenaza
Name: Incidente, dtype: object

In [5]:
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, precision_score, recall_score, accuracy_score, f1_score
#from sklearn.model_selection import cross_validate
clf = MLPClassifier(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(5,4))
#from sklearn.model_selection import cross_val_score
#scoring = ['precision', 'recall', 'accuracy']
#scores = cross_validate(clf, X_svd, y, cv=5, scoring=scoring, return_train_score=False)
#print(scores)

# Split the data into a training set and a test set
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

In [6]:
X_test.head()

Codigo DANE  Dia = Lunes  Dia = Martes  Dia = Miercoles  \
129575     0.749166            0             0                0   
157356     0.063310            0             1                0   
131934     0.754643            0             0                0   
70442      0.474824            0             1                0   
67625      0.063310            0             0                0   

        Dia = Viernes  Dia = Jueves  Dia = Sabado  Dia = Domingo  \
129575              1             0             0              0   
157356              0             0             0              0   
131934              0             0             1              0   
70442               0             0             0              0   
67625               0             1             0              0   

        Arma empleada = ARMA BLANCA / CORTOPUNZANTE  \
129575                                            0   
157356                                            0   
131934                                            0   
70442                                             0   
67625                                             0   

        Arma empleada = SIN EMPLEO DE ARMAS  ...  Arma empleada = JERINGA  \
129575                                    0  ...                        0   
157356                                    0  ...                        0   
131934                                    0  ...                        0   
70442                                     0  ...                        0   
67625                                     1  ...                        0   

        Arma empleada = -  Arma empleada = VEHICULO  Arma empleada = MOTO  \
129575                  0                         0                     0   
157356                  0                         0                     0   
131934                  0                         0                     0   
70442                   0                         0                     0   
67625                   0                         0                     0   

        Arma empleada = BICICLETA  Sexo = MASCULINO  Sexo = FEMENINO  \
129575                          0                 0                1   
157356                          0                 1                0   
131934                          0                 0                1   
70442                           0                 1                0   
67625                           0                 0                1   

        Sexo = -  Edad  clase  
129575         0  43.0    3.0  
157356         0  33.0    4.0  
131934         0  44.0    4.0  
70442          0  39.0    2.0  
67625          0  42.0    2.0  

[5 rows x 40 columns]

In [7]:
X_train.head()

Codigo DANE  Dia = Lunes  Dia = Martes  Dia = Miercoles  \
144361     0.031655            0             0                0   
53365      0.752058            0             0                1   
50106      0.521293            1             0                0   
106496     0.664753            0             0                0   
130961     0.063310            0             0                0   

        Dia = Viernes  Dia = Jueves  Dia = Sabado  Dia = Domingo  \
144361              0             0             1              0   
53365               0             0             0              0   
50106               0             0             0              0   
106496              0             1             0              0   
130961              1             0             0              0   

        Arma empleada = ARMA BLANCA / CORTOPUNZANTE  \
144361                                            0   
53365                                             0   
50106                                             0   
106496                                            0   
130961                                            0   

        Arma empleada = SIN EMPLEO DE ARMAS  ...  Arma empleada = JERINGA  \
144361                                    0  ...                        0   
53365                                     0  ...                        0   
50106                                     0  ...                        0   
106496                                    1  ...                        0   
130961                                    0  ...                        0   

        Arma empleada = -  Arma empleada = VEHICULO  Arma empleada = MOTO  \
144361                  0                         0                     0   
53365                   0                         0                     0   
50106                   0                         0                     0   
106496                  0                         0                     0   
130961                  0                         0                     0   

        Arma empleada = BICICLETA  Sexo = MASCULINO  Sexo = FEMENINO  \
144361                          0                 1                0   
53365                           0                 1                0   
50106                           0                 0                1   
106496                          0                 0                1   
130961                          0                 1                0   

        Sexo = -  Edad  clase  
144361         0  37.0    4.0  
53365          0  21.0    2.0  
50106          0  31.0    2.0  
106496         0  19.0    2.0  
130961         0  22.0    3.0  

[5 rows x 40 columns]

In [8]:
clf.fit(X_train,y_train)

MLPClassifier(activation='relu', alpha=1e-05, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(5, 4), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='lbfgs', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [9]:
y_pred = clf.predict(X_test)
confusion_matrix(y_test, y_pred)

array([[ 9797,     0,     0,     0,     0,     0],
       [   50,  1969,    12,     0,     0,     0],
       [    0,     0, 18851,     7,     0,     1],
       [    0,     0,     1,  3313,     0,  3409],
       [    0,     0,    98,  1075,     0,   851],
       [    0,     0,    17,   798,     0,  6919]], dtype=int64)

In [10]:
recall_score(y_test, y_pred, average=None)

array([1.        , 0.96947317, 0.9995758 , 0.49278596, 0.        ,
       0.89462115])

In [11]:
precision_score(y_test, y_pred, average=None)

C:\Users\Camilo\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1143: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


array([0.99492231, 1.        , 0.9932557 , 0.6379742 , 0.        ,
       0.61887299])

In [12]:
accuracy_score(y_test, y_pred)

0.8660320556309362

In [13]:
from sklearn_porter import Porter

In [14]:
porter = Porter(clf, language='js')
output = porter.export(embed_data=True)
print(output)

var MLPClassifier = function(hidden, output, layers, weights, bias) {

    this.hidden = hidden.toUpperCase();
    this.output = output.toUpperCase();
    this.network = new Array(layers.length + 1);
    for (var i = 0, l = layers.length; i < l; i++) {
        this.network[i + 1] = new Array(layers[i]).fill(0.);
    }
    this.weights = weights;
    this.bias = bias;

    var compute = function(activation, v) {
        switch (activation) {
            case 'LOGISTIC':
                for (var i = 0, l = v.length; i < l; i++) {
                    v[i] = 1. / (1. + Math.exp(-v[i]));
                }
                break;
            case 'RELU':
                for (var i = 0, l = v.length; i < l; i++) {
                    v[i] = Math.max(0, v[i]);
                }
                break;
            case 'TANH':
                for (var i = 0, l = v.length; i < l; i++) {
                    v[i] = Math.tanh(v[i]);
                }
                break;
            case 'SOFTMAX':